[project]
name = "codespaces-blank"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "ipykernel>=6.29.5",
    "loguru>=0.7.3",
    "requests>=2.32.3",
    "setuptools>=75.8.0",
    "undetected-chromedriver>=3.5.5",
]
